version: '3.8'

services:
  frontend:
    build:
      context: .
      target: production
    container_name: frontend-rpi
    ports:
      - "80:80"
    env_file:
      - .env.rpi
    environment:
      - NODE_ENV=production
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 256M
        reservations:
          cpus: '0.2'
          memory: 128M 