apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: frontend
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "3"
        run.googleapis.com/container-dependencies: '{"nginx": ["rendertron"]}'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - name: nginx
          image: ${NGINX_IMAGE}
          ports:
            - containerPort: 80
              name: http1
          resources:
            limits:
              cpu: "1"
              memory: "256Mi"
          startupProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3

        - name: rendertron
          image: ${RENDERTRON_IMAGE}
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
          startupProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 8
          env:
            - name: PORT
              value: "3000" 