tunnel: your-tunnel-id
credentials-file: /etc/cloudflared/credentials.json

ingress:
  # Point the main domain and www subdomain to the frontend
  - hostname: aoyamaxx.com
    service: http://localhost:80
  - hostname: www.aoyamaxx.com
    service: http://localhost:80
  
  # Point the api subdomain to the backend
  - hostname: api.aoyamaxx.com
    service: http://localhost:8000
  
  # Capture all other requests and return 404
  - service: http_status:404 