# Generated by Django 4.2.20 on 2025-03-15 12:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('port_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=3)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'ports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('imo_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mmsi', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=255)),
                ('ship_type', models.IntegerField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('max_draught', models.FloatField(blank=True, null=True)),
                ('type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('type_remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ships',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShipData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imo_number', models.CharField(max_length=20)),
                ('timestamp_ais', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ship_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PortContent',
            fields=[
                ('port_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=3)),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('policy_status', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Port Content',
                'verbose_name_plural': 'Port Contents',
                'db_table': 'port_content',
            },
        ),
    ]
