# Generated by Django 4.2.20 on 2025-04-08 00:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('north_sea_watch', '0002_usertracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICCTScrubberMarch2025',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imo_number', models.CharField(max_length=20)),
                ('sox_scrubber_status', models.CharField(blank=True, max_length=255, null=True)),
                ('sox_scrubber_1_technology_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'icct_scrubber_march_2025',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ICCTWFRCombined',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imo_number', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'icct_wfr_combined',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='portcontent',
            name='additional_features',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portcontent',
            name='infrastructure_capacity',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portcontent',
            name='operational_statistics',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
